# Generated by Django 5.1.7 on 2025-04-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_perfil_profesional_reserva_profesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
