# Generated by Django 5.1.7 on 2025-03-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('fecha', 'hora')},
        ),
    ]
